/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package sequence;

/**
 *
 * @author dell
 */
public class Tablero extends javax.swing.JFrame {

    /**
     * Creates new form Tablero
     */
    public Tablero() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        jButton17 = new javax.swing.JButton();
        jButton18 = new javax.swing.JButton();
        jButton19 = new javax.swing.JButton();
        jButton20 = new javax.swing.JButton();
        jButton21 = new javax.swing.JButton();
        jButton22 = new javax.swing.JButton();
        jButton23 = new javax.swing.JButton();
        jButton24 = new javax.swing.JButton();
        jButton25 = new javax.swing.JButton();
        jButton26 = new javax.swing.JButton();
        jButton27 = new javax.swing.JButton();
        jButton28 = new javax.swing.JButton();
        jButton29 = new javax.swing.JButton();
        jButton30 = new javax.swing.JButton();
        jButton31 = new javax.swing.JButton();
        jButton32 = new javax.swing.JButton();
        jButton33 = new javax.swing.JButton();
        jButton34 = new javax.swing.JButton();
        jButton35 = new javax.swing.JButton();
        jButton36 = new javax.swing.JButton();
        jButton37 = new javax.swing.JButton();
        jButton38 = new javax.swing.JButton();
        jButton39 = new javax.swing.JButton();
        jButton40 = new javax.swing.JButton();
        jButton41 = new javax.swing.JButton();
        jButton42 = new javax.swing.JButton();
        jButton43 = new javax.swing.JButton();
        jButton44 = new javax.swing.JButton();
        jButton45 = new javax.swing.JButton();
        jButton46 = new javax.swing.JButton();
        jButton47 = new javax.swing.JButton();
        jButton48 = new javax.swing.JButton();
        jButton49 = new javax.swing.JButton();
        jButton50 = new javax.swing.JButton();
        jButton51 = new javax.swing.JButton();
        jButton52 = new javax.swing.JButton();
        jButton53 = new javax.swing.JButton();
        jButton54 = new javax.swing.JButton();
        jButton55 = new javax.swing.JButton();
        jButton56 = new javax.swing.JButton();
        jButton57 = new javax.swing.JButton();
        jButton58 = new javax.swing.JButton();
        jButton59 = new javax.swing.JButton();
        jButton60 = new javax.swing.JButton();
        jButton61 = new javax.swing.JButton();
        jButton62 = new javax.swing.JButton();
        jButton63 = new javax.swing.JButton();
        jButton64 = new javax.swing.JButton();
        jButton65 = new javax.swing.JButton();
        jButton66 = new javax.swing.JButton();
        jButton67 = new javax.swing.JButton();
        jButton68 = new javax.swing.JButton();
        jButton69 = new javax.swing.JButton();
        jButton70 = new javax.swing.JButton();
        jButton71 = new javax.swing.JButton();
        jButton72 = new javax.swing.JButton();
        jButton73 = new javax.swing.JButton();
        jButton74 = new javax.swing.JButton();
        jButton75 = new javax.swing.JButton();
        jButton76 = new javax.swing.JButton();
        jButton77 = new javax.swing.JButton();
        jButton78 = new javax.swing.JButton();
        jButton79 = new javax.swing.JButton();
        jButton80 = new javax.swing.JButton();
        jButton81 = new javax.swing.JButton();
        jButton82 = new javax.swing.JButton();
        jButton83 = new javax.swing.JButton();
        jButton84 = new javax.swing.JButton();
        jButton85 = new javax.swing.JButton();
        jButton86 = new javax.swing.JButton();
        jButton87 = new javax.swing.JButton();
        jButton88 = new javax.swing.JButton();
        jButton89 = new javax.swing.JButton();
        jButton90 = new javax.swing.JButton();
        jButton91 = new javax.swing.JButton();
        jButton92 = new javax.swing.JButton();
        jButton93 = new javax.swing.JButton();
        jButton94 = new javax.swing.JButton();
        jButton95 = new javax.swing.JButton();
        jButton96 = new javax.swing.JButton();
        jButton97 = new javax.swing.JButton();
        jButton98 = new javax.swing.JButton();
        jButton99 = new javax.swing.JButton();
        jButton100 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Mazo2 = new javax.swing.JPanel();
        jButton102 = new javax.swing.JButton();
        jButton103 = new javax.swing.JButton();
        jButton104 = new javax.swing.JButton();
        jButton105 = new javax.swing.JButton();
        jButton106 = new javax.swing.JButton();
        jButton107 = new javax.swing.JButton();
        jButton108 = new javax.swing.JButton();
        jButton109 = new javax.swing.JButton();
        Mazo = new javax.swing.JButton();
        NombreMazoTurno = new javax.swing.JLabel();
        tiempoLabel = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        CardUsed = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        instrucDiscart = new javax.swing.JLabel();
        cartaSelec = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jButton101 = new javax.swing.JButton();
        instrucOrdenar = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        secuenciaComp = new javax.swing.JLabel();
        secCarta2 = new javax.swing.JLabel();
        secCarta3 = new javax.swing.JLabel();
        secCarta5 = new javax.swing.JLabel();
        secCarta1 = new javax.swing.JLabel();
        secCarta4 = new javax.swing.JLabel();
        turnoEquipo = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 68, 52));

        jButton2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(68, 0, 68, 52));

        jButton3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(136, 0, 68, 52));

        jButton4.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(204, 0, 68, 52));

        jButton5.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(272, 0, 68, 52));

        jButton6.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 0, 68, 52));

        jButton7.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(408, 0, 68, 52));

        jButton8.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(476, 0, 68, 52));

        jButton9.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(544, 0, 68, 52));

        jButton10.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(jButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(612, 0, 68, 52));

        jButton11.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(jButton11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 52, 68, 52));

        jButton12.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(jButton12, new org.netbeans.lib.awtextra.AbsoluteConstraints(68, 52, 68, 52));

        jButton13.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(jButton13, new org.netbeans.lib.awtextra.AbsoluteConstraints(136, 52, 68, 52));

        jButton14.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(jButton14, new org.netbeans.lib.awtextra.AbsoluteConstraints(204, 52, 68, 52));

        jButton15.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(jButton15, new org.netbeans.lib.awtextra.AbsoluteConstraints(272, 52, 68, 52));

        jButton16.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(jButton16, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 52, 68, 52));

        jButton17.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(jButton17, new org.netbeans.lib.awtextra.AbsoluteConstraints(408, 52, 68, 52));

        jButton18.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(jButton18, new org.netbeans.lib.awtextra.AbsoluteConstraints(476, 52, 68, 52));

        jButton19.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(jButton19, new org.netbeans.lib.awtextra.AbsoluteConstraints(544, 52, 68, 52));

        jButton20.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(jButton20, new org.netbeans.lib.awtextra.AbsoluteConstraints(612, 52, 68, 52));

        jButton21.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(jButton21, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 104, 68, 52));

        jButton22.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(jButton22, new org.netbeans.lib.awtextra.AbsoluteConstraints(68, 104, 68, 52));

        jButton23.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(jButton23, new org.netbeans.lib.awtextra.AbsoluteConstraints(136, 104, 68, 52));

        jButton24.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(jButton24, new org.netbeans.lib.awtextra.AbsoluteConstraints(204, 104, 68, 52));

        jButton25.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(jButton25, new org.netbeans.lib.awtextra.AbsoluteConstraints(272, 104, 68, 52));

        jButton26.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(jButton26, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 104, 68, 52));

        jButton27.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(jButton27, new org.netbeans.lib.awtextra.AbsoluteConstraints(408, 104, 68, 52));

        jButton28.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(jButton28, new org.netbeans.lib.awtextra.AbsoluteConstraints(476, 104, 68, 52));

        jButton29.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(jButton29, new org.netbeans.lib.awtextra.AbsoluteConstraints(544, 104, 68, 52));

        jButton30.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(jButton30, new org.netbeans.lib.awtextra.AbsoluteConstraints(612, 104, 68, 52));

        jButton31.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(jButton31, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 156, 68, 52));

        jButton32.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(jButton32, new org.netbeans.lib.awtextra.AbsoluteConstraints(68, 156, 68, 52));

        jButton33.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(jButton33, new org.netbeans.lib.awtextra.AbsoluteConstraints(136, 156, 68, 52));

        jButton34.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(jButton34, new org.netbeans.lib.awtextra.AbsoluteConstraints(204, 156, 68, 52));

        jButton35.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(jButton35, new org.netbeans.lib.awtextra.AbsoluteConstraints(272, 156, 68, 52));

        jButton36.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(jButton36, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 156, 68, 52));

        jButton37.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(jButton37, new org.netbeans.lib.awtextra.AbsoluteConstraints(408, 156, 68, 52));

        jButton38.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(jButton38, new org.netbeans.lib.awtextra.AbsoluteConstraints(476, 156, 68, 52));

        jButton39.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(jButton39, new org.netbeans.lib.awtextra.AbsoluteConstraints(544, 156, 68, 52));

        jButton40.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(jButton40, new org.netbeans.lib.awtextra.AbsoluteConstraints(612, 156, 68, 52));

        jButton41.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(jButton41, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 208, 68, 52));

        jButton42.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(jButton42, new org.netbeans.lib.awtextra.AbsoluteConstraints(68, 208, 68, 52));

        jButton43.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(jButton43, new org.netbeans.lib.awtextra.AbsoluteConstraints(136, 208, 68, 52));

        jButton44.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(jButton44, new org.netbeans.lib.awtextra.AbsoluteConstraints(204, 208, 68, 52));

        jButton45.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(jButton45, new org.netbeans.lib.awtextra.AbsoluteConstraints(272, 208, 68, 52));

        jButton46.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(jButton46, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 208, 68, 52));

        jButton47.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(jButton47, new org.netbeans.lib.awtextra.AbsoluteConstraints(408, 208, 68, 52));

        jButton48.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(jButton48, new org.netbeans.lib.awtextra.AbsoluteConstraints(476, 208, 68, 52));

        jButton49.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(jButton49, new org.netbeans.lib.awtextra.AbsoluteConstraints(544, 208, 68, 52));

        jButton50.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(jButton50, new org.netbeans.lib.awtextra.AbsoluteConstraints(612, 208, 68, 52));

        jButton51.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(jButton51, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 260, 68, 52));

        jButton52.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(jButton52, new org.netbeans.lib.awtextra.AbsoluteConstraints(68, 260, 68, 52));

        jButton53.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(jButton53, new org.netbeans.lib.awtextra.AbsoluteConstraints(136, 260, 68, 52));

        jButton54.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(jButton54, new org.netbeans.lib.awtextra.AbsoluteConstraints(204, 260, 68, 52));

        jButton55.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(jButton55, new org.netbeans.lib.awtextra.AbsoluteConstraints(272, 260, 68, 52));

        jButton56.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(jButton56, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 260, 68, 52));

        jButton57.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(jButton57, new org.netbeans.lib.awtextra.AbsoluteConstraints(408, 260, 68, 52));

        jButton58.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(jButton58, new org.netbeans.lib.awtextra.AbsoluteConstraints(476, 260, 68, 52));

        jButton59.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(jButton59, new org.netbeans.lib.awtextra.AbsoluteConstraints(544, 260, 68, 52));

        jButton60.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(jButton60, new org.netbeans.lib.awtextra.AbsoluteConstraints(612, 260, 68, 52));

        jButton61.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(jButton61, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 312, 68, 52));

        jButton62.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(jButton62, new org.netbeans.lib.awtextra.AbsoluteConstraints(68, 312, 68, 52));

        jButton63.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(jButton63, new org.netbeans.lib.awtextra.AbsoluteConstraints(136, 312, 68, 52));

        jButton64.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(jButton64, new org.netbeans.lib.awtextra.AbsoluteConstraints(204, 312, 68, 52));

        jButton65.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(jButton65, new org.netbeans.lib.awtextra.AbsoluteConstraints(272, 312, 68, 52));

        jButton66.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(jButton66, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 312, 68, 52));

        jButton67.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButton67.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton67ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton67, new org.netbeans.lib.awtextra.AbsoluteConstraints(408, 312, 68, 52));

        jButton68.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(jButton68, new org.netbeans.lib.awtextra.AbsoluteConstraints(476, 312, 68, 52));

        jButton69.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(jButton69, new org.netbeans.lib.awtextra.AbsoluteConstraints(544, 312, 68, 52));

        jButton70.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(jButton70, new org.netbeans.lib.awtextra.AbsoluteConstraints(612, 312, 68, 52));

        jButton71.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(jButton71, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 364, 68, 52));

        jButton72.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(jButton72, new org.netbeans.lib.awtextra.AbsoluteConstraints(68, 364, 68, 52));

        jButton73.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(jButton73, new org.netbeans.lib.awtextra.AbsoluteConstraints(136, 364, 68, 52));

        jButton74.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(jButton74, new org.netbeans.lib.awtextra.AbsoluteConstraints(204, 364, 68, 52));

        jButton75.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(jButton75, new org.netbeans.lib.awtextra.AbsoluteConstraints(272, 364, 68, 52));

        jButton76.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(jButton76, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 364, 68, 52));

        jButton77.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(jButton77, new org.netbeans.lib.awtextra.AbsoluteConstraints(408, 364, 68, 52));

        jButton78.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(jButton78, new org.netbeans.lib.awtextra.AbsoluteConstraints(476, 364, 68, 52));

        jButton79.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(jButton79, new org.netbeans.lib.awtextra.AbsoluteConstraints(544, 364, 68, 52));

        jButton80.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(jButton80, new org.netbeans.lib.awtextra.AbsoluteConstraints(612, 364, 68, 52));

        jButton81.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(jButton81, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 416, 68, 52));

        jButton82.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(jButton82, new org.netbeans.lib.awtextra.AbsoluteConstraints(68, 416, 68, 52));

        jButton83.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(jButton83, new org.netbeans.lib.awtextra.AbsoluteConstraints(136, 416, 68, 52));

        jButton84.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(jButton84, new org.netbeans.lib.awtextra.AbsoluteConstraints(204, 416, 68, 52));

        jButton85.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(jButton85, new org.netbeans.lib.awtextra.AbsoluteConstraints(272, 416, 68, 52));

        jButton86.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(jButton86, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 416, 68, 52));

        jButton87.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(jButton87, new org.netbeans.lib.awtextra.AbsoluteConstraints(408, 416, 68, 52));

        jButton88.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(jButton88, new org.netbeans.lib.awtextra.AbsoluteConstraints(476, 416, 68, 52));

        jButton89.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(jButton89, new org.netbeans.lib.awtextra.AbsoluteConstraints(544, 416, 68, 52));

        jButton90.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(jButton90, new org.netbeans.lib.awtextra.AbsoluteConstraints(612, 416, 68, 52));

        jButton91.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(jButton91, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 468, 68, 52));

        jButton92.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(jButton92, new org.netbeans.lib.awtextra.AbsoluteConstraints(68, 468, 68, 52));

        jButton93.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(jButton93, new org.netbeans.lib.awtextra.AbsoluteConstraints(136, 468, 68, 52));

        jButton94.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(jButton94, new org.netbeans.lib.awtextra.AbsoluteConstraints(204, 468, 68, 52));

        jButton95.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(jButton95, new org.netbeans.lib.awtextra.AbsoluteConstraints(272, 468, 68, 52));

        jButton96.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(jButton96, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 468, 68, 52));

        jButton97.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(jButton97, new org.netbeans.lib.awtextra.AbsoluteConstraints(408, 468, 68, 52));

        jButton98.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(jButton98, new org.netbeans.lib.awtextra.AbsoluteConstraints(476, 468, 68, 52));

        jButton99.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(jButton99, new org.netbeans.lib.awtextra.AbsoluteConstraints(544, 468, 68, 52));

        jButton100.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButton100.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton100ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton100, new org.netbeans.lib.awtextra.AbsoluteConstraints(612, 468, 68, 52));

        jLabel3.setText("jLabel3");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 70, 50));

        jLabel4.setText("jLabel4");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 680, 520));

        Mazo2.setBackground(new java.awt.Color(51, 51, 51));
        Mazo2.setBorder(new javax.swing.border.MatteBorder(null));
        Mazo2.setForeground(new java.awt.Color(0, 0, 0));
        Mazo2.setLayout(new java.awt.GridLayout(2, 3));

        jButton102.setBackground(new java.awt.Color(102, 102, 102));
        jButton102.setForeground(new java.awt.Color(0, 0, 0));
        jButton102.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        Mazo2.add(jButton102);

        jButton103.setBackground(new java.awt.Color(102, 102, 102));
        jButton103.setForeground(new java.awt.Color(0, 0, 0));
        jButton103.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        Mazo2.add(jButton103);

        jButton104.setBackground(new java.awt.Color(102, 102, 102));
        jButton104.setForeground(new java.awt.Color(0, 0, 0));
        jButton104.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        Mazo2.add(jButton104);

        jButton105.setBackground(new java.awt.Color(102, 102, 102));
        jButton105.setForeground(new java.awt.Color(0, 0, 0));
        jButton105.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        Mazo2.add(jButton105);

        jButton106.setBackground(new java.awt.Color(102, 102, 102));
        jButton106.setForeground(new java.awt.Color(0, 0, 0));
        jButton106.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        Mazo2.add(jButton106);

        jButton107.setBackground(new java.awt.Color(102, 102, 102));
        jButton107.setForeground(new java.awt.Color(0, 0, 0));
        jButton107.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        Mazo2.add(jButton107);

        jButton108.setBackground(new java.awt.Color(102, 102, 102));
        jButton108.setForeground(new java.awt.Color(0, 0, 0));
        jButton108.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        Mazo2.add(jButton108);

        jButton109.setBackground(new java.awt.Color(102, 102, 102));
        jButton109.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        Mazo2.add(jButton109);

        getContentPane().add(Mazo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 250, 260, 110));

        Mazo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/parteTrasera.png"))); // NOI18N
        Mazo.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        Mazo.setBorderPainted(false);
        Mazo.setContentAreaFilled(false);
        Mazo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MazoActionPerformed(evt);
            }
        });
        getContentPane().add(Mazo, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 470, 75, 55));

        NombreMazoTurno.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        NombreMazoTurno.setText("Mazo Jugador 1");
        getContentPane().add(NombreMazoTurno, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 230, 190, -1));

        tiempoLabel.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        tiempoLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tiempoLabel.setText("02:00");
        tiempoLabel.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(41, 43, 45)), "TIEMPO RESTANTE", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.BELOW_TOP, new java.awt.Font("Dialog", 0, 12), new java.awt.Color(0, 0, 0))); // NOI18N
        tiempoLabel.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        getContentPane().add(tiempoLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 560, 150, 70));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Ordenar");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 430, 75, 55));

        CardUsed.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        CardUsed.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/parteTrasera.png"))); // NOI18N
        getContentPane().add(CardUsed, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 30, 130, 60));

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("En Turno Anterior");
        jLabel5.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 90, 180, -1));

        instrucDiscart.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        instrucDiscart.setText("<html> Elige la carta de tu mazo que deseas descartar <html>");
        getContentPane().add(instrucDiscart, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 360, 280, 20));

        cartaSelec.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cartaSelec.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/parteTrasera.png"))); // NOI18N
        getContentPane().add(cartaSelec, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 150, 170, 50));

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Carta Seleccionada");
        jLabel6.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 120, 190, -1));

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Carta Utilizada");
        jLabel7.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 10, 150, -1));

        jButton101.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/orden.png"))); // NOI18N
        jButton101.setBorderPainted(false);
        jButton101.setContentAreaFilled(false);
        jButton101.setVerifyInputWhenFocusTarget(false);
        jButton101.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        getContentPane().add(jButton101, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 470, -1, -1));

        instrucOrdenar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        instrucOrdenar.setText("<html> Para dejar de ordenar las cartas y volver a jugar oprima de nuevo el boton de ordenar <html>");
        getContentPane().add(instrucOrdenar, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 360, 260, -1));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 630, 40, 40));

        secuenciaComp.setText("Todavia no se ha completado ninguna secuencia");
        getContentPane().add(secuenciaComp, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 330, -1));

        secCarta2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/parteTrasera.png"))); // NOI18N
        getContentPane().add(secCarta2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 50, 80, 50));

        secCarta3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/parteTrasera.png"))); // NOI18N
        getContentPane().add(secCarta3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 50, 80, 50));

        secCarta5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/parteTrasera.png"))); // NOI18N
        getContentPane().add(secCarta5, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 50, 80, 50));

        secCarta1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/parteTrasera.png"))); // NOI18N
        getContentPane().add(secCarta1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, 80, 50));

        secCarta4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/parteTrasera.png"))); // NOI18N
        getContentPane().add(secCarta4, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 50, 80, 50));

        turnoEquipo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        turnoEquipo.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(41, 43, 45)), "Turno ", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));
        getContentPane().add(turnoEquipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 30, 140, 60));

        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Mazo Comun");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 430, 75, 55));

        jLabel11.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(41, 43, 45)), "Ultima Secuencia Completada", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.DEFAULT_POSITION));
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 380, 100));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton100ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton100ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton100ActionPerformed

    private void jButton67ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton67ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton67ActionPerformed

    private void MazoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MazoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MazoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tablero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tablero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tablero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tablero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tablero().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JLabel CardUsed;
    public static javax.swing.JButton Mazo;
    private javax.swing.JPanel Mazo2;
    public static javax.swing.JLabel NombreMazoTurno;
    public static javax.swing.JLabel cartaSelec;
    public static javax.swing.JLabel instrucDiscart;
    public static javax.swing.JLabel instrucOrdenar;
    public static javax.swing.JButton jButton1;
    public static javax.swing.JButton jButton10;
    public static javax.swing.JButton jButton100;
    public static javax.swing.JButton jButton101;
    public static javax.swing.JButton jButton102;
    public static javax.swing.JButton jButton103;
    public static javax.swing.JButton jButton104;
    public static javax.swing.JButton jButton105;
    public static javax.swing.JButton jButton106;
    public static javax.swing.JButton jButton107;
    public static javax.swing.JButton jButton108;
    public static javax.swing.JButton jButton109;
    public static javax.swing.JButton jButton11;
    public static javax.swing.JButton jButton12;
    public static javax.swing.JButton jButton13;
    public static javax.swing.JButton jButton14;
    public static javax.swing.JButton jButton15;
    public static javax.swing.JButton jButton16;
    public static javax.swing.JButton jButton17;
    public static javax.swing.JButton jButton18;
    public static javax.swing.JButton jButton19;
    public static javax.swing.JButton jButton2;
    public static javax.swing.JButton jButton20;
    public static javax.swing.JButton jButton21;
    public static javax.swing.JButton jButton22;
    public static javax.swing.JButton jButton23;
    public static javax.swing.JButton jButton24;
    public static javax.swing.JButton jButton25;
    public static javax.swing.JButton jButton26;
    public static javax.swing.JButton jButton27;
    public static javax.swing.JButton jButton28;
    public static javax.swing.JButton jButton29;
    public static javax.swing.JButton jButton3;
    public static javax.swing.JButton jButton30;
    public static javax.swing.JButton jButton31;
    public static javax.swing.JButton jButton32;
    public static javax.swing.JButton jButton33;
    public static javax.swing.JButton jButton34;
    public static javax.swing.JButton jButton35;
    public static javax.swing.JButton jButton36;
    public static javax.swing.JButton jButton37;
    public static javax.swing.JButton jButton38;
    public static javax.swing.JButton jButton39;
    public static javax.swing.JButton jButton4;
    public static javax.swing.JButton jButton40;
    public static javax.swing.JButton jButton41;
    public static javax.swing.JButton jButton42;
    public static javax.swing.JButton jButton43;
    public static javax.swing.JButton jButton44;
    public static javax.swing.JButton jButton45;
    public static javax.swing.JButton jButton46;
    public static javax.swing.JButton jButton47;
    public static javax.swing.JButton jButton48;
    public static javax.swing.JButton jButton49;
    public static javax.swing.JButton jButton5;
    public static javax.swing.JButton jButton50;
    public static javax.swing.JButton jButton51;
    public static javax.swing.JButton jButton52;
    public static javax.swing.JButton jButton53;
    public static javax.swing.JButton jButton54;
    public static javax.swing.JButton jButton55;
    public static javax.swing.JButton jButton56;
    public static javax.swing.JButton jButton57;
    public static javax.swing.JButton jButton58;
    public static javax.swing.JButton jButton59;
    public static javax.swing.JButton jButton6;
    public static javax.swing.JButton jButton60;
    public static javax.swing.JButton jButton61;
    public static javax.swing.JButton jButton62;
    public static javax.swing.JButton jButton63;
    public static javax.swing.JButton jButton64;
    public static javax.swing.JButton jButton65;
    public static javax.swing.JButton jButton66;
    public static javax.swing.JButton jButton67;
    public static javax.swing.JButton jButton68;
    public static javax.swing.JButton jButton69;
    public static javax.swing.JButton jButton7;
    public static javax.swing.JButton jButton70;
    public static javax.swing.JButton jButton71;
    public static javax.swing.JButton jButton72;
    public static javax.swing.JButton jButton73;
    public static javax.swing.JButton jButton74;
    public static javax.swing.JButton jButton75;
    public static javax.swing.JButton jButton76;
    public static javax.swing.JButton jButton77;
    public static javax.swing.JButton jButton78;
    public static javax.swing.JButton jButton79;
    public static javax.swing.JButton jButton8;
    public static javax.swing.JButton jButton80;
    public static javax.swing.JButton jButton81;
    public static javax.swing.JButton jButton82;
    public static javax.swing.JButton jButton83;
    public static javax.swing.JButton jButton84;
    public static javax.swing.JButton jButton85;
    public static javax.swing.JButton jButton86;
    public static javax.swing.JButton jButton87;
    public static javax.swing.JButton jButton88;
    public static javax.swing.JButton jButton89;
    public static javax.swing.JButton jButton9;
    public static javax.swing.JButton jButton90;
    public static javax.swing.JButton jButton91;
    public static javax.swing.JButton jButton92;
    public static javax.swing.JButton jButton93;
    public static javax.swing.JButton jButton94;
    public static javax.swing.JButton jButton95;
    public static javax.swing.JButton jButton96;
    public static javax.swing.JButton jButton97;
    public static javax.swing.JButton jButton98;
    public static javax.swing.JButton jButton99;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    public static javax.swing.JLabel secCarta1;
    public static javax.swing.JLabel secCarta2;
    public static javax.swing.JLabel secCarta3;
    public static javax.swing.JLabel secCarta4;
    public static javax.swing.JLabel secCarta5;
    public static javax.swing.JLabel secuenciaComp;
    public static javax.swing.JLabel tiempoLabel;
    public static javax.swing.JLabel turnoEquipo;
    // End of variables declaration//GEN-END:variables
}
