/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package sequence;

/**
 *
 * @author dell
 */
public class Tablero extends javax.swing.JFrame {

    /**
     * Creates new form Tablero
     */
    public Tablero() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        jButton17 = new javax.swing.JButton();
        jButton18 = new javax.swing.JButton();
        jButton19 = new javax.swing.JButton();
        jButton20 = new javax.swing.JButton();
        jButton21 = new javax.swing.JButton();
        jButton22 = new javax.swing.JButton();
        jButton23 = new javax.swing.JButton();
        jButton24 = new javax.swing.JButton();
        jButton25 = new javax.swing.JButton();
        jButton26 = new javax.swing.JButton();
        jButton27 = new javax.swing.JButton();
        jButton28 = new javax.swing.JButton();
        jButton29 = new javax.swing.JButton();
        jButton30 = new javax.swing.JButton();
        jButton31 = new javax.swing.JButton();
        jButton32 = new javax.swing.JButton();
        jButton33 = new javax.swing.JButton();
        jButton34 = new javax.swing.JButton();
        jButton35 = new javax.swing.JButton();
        jButton36 = new javax.swing.JButton();
        jButton37 = new javax.swing.JButton();
        jButton38 = new javax.swing.JButton();
        jButton39 = new javax.swing.JButton();
        jButton40 = new javax.swing.JButton();
        jButton41 = new javax.swing.JButton();
        jButton42 = new javax.swing.JButton();
        jButton43 = new javax.swing.JButton();
        jButton44 = new javax.swing.JButton();
        jButton45 = new javax.swing.JButton();
        jButton46 = new javax.swing.JButton();
        jButton47 = new javax.swing.JButton();
        jButton48 = new javax.swing.JButton();
        jButton49 = new javax.swing.JButton();
        jButton50 = new javax.swing.JButton();
        jButton51 = new javax.swing.JButton();
        jButton52 = new javax.swing.JButton();
        jButton53 = new javax.swing.JButton();
        jButton54 = new javax.swing.JButton();
        jButton55 = new javax.swing.JButton();
        jButton56 = new javax.swing.JButton();
        jButton57 = new javax.swing.JButton();
        jButton58 = new javax.swing.JButton();
        jButton59 = new javax.swing.JButton();
        jButton60 = new javax.swing.JButton();
        jButton61 = new javax.swing.JButton();
        jButton62 = new javax.swing.JButton();
        jButton63 = new javax.swing.JButton();
        jButton64 = new javax.swing.JButton();
        jButton65 = new javax.swing.JButton();
        jButton66 = new javax.swing.JButton();
        jButton67 = new javax.swing.JButton();
        jButton68 = new javax.swing.JButton();
        jButton69 = new javax.swing.JButton();
        jButton70 = new javax.swing.JButton();
        jButton71 = new javax.swing.JButton();
        jButton72 = new javax.swing.JButton();
        jButton73 = new javax.swing.JButton();
        jButton74 = new javax.swing.JButton();
        jButton75 = new javax.swing.JButton();
        jButton76 = new javax.swing.JButton();
        jButton77 = new javax.swing.JButton();
        jButton78 = new javax.swing.JButton();
        jButton79 = new javax.swing.JButton();
        jButton80 = new javax.swing.JButton();
        jButton81 = new javax.swing.JButton();
        jButton82 = new javax.swing.JButton();
        jButton83 = new javax.swing.JButton();
        jButton84 = new javax.swing.JButton();
        jButton85 = new javax.swing.JButton();
        jButton86 = new javax.swing.JButton();
        jButton87 = new javax.swing.JButton();
        jButton88 = new javax.swing.JButton();
        jButton89 = new javax.swing.JButton();
        jButton90 = new javax.swing.JButton();
        jButton91 = new javax.swing.JButton();
        jButton92 = new javax.swing.JButton();
        jButton93 = new javax.swing.JButton();
        jButton94 = new javax.swing.JButton();
        jButton95 = new javax.swing.JButton();
        jButton96 = new javax.swing.JButton();
        jButton97 = new javax.swing.JButton();
        jButton98 = new javax.swing.JButton();
        jButton99 = new javax.swing.JButton();
        jButton100 = new javax.swing.JButton();
        Mazo2 = new javax.swing.JPanel();
        jButton102 = new javax.swing.JButton();
        jButton103 = new javax.swing.JButton();
        jButton104 = new javax.swing.JButton();
        jButton105 = new javax.swing.JButton();
        jButton106 = new javax.swing.JButton();
        jButton107 = new javax.swing.JButton();
        Mazo = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        NombreMazoTurno = new javax.swing.JLabel();
        jButton101 = new javax.swing.JButton();
        tiempoLabel = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new java.awt.GridLayout(10, 10));

        jButton1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(jButton1);

        jButton2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(jButton2);

        jButton3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(jButton3);

        jButton4.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(jButton4);

        jButton5.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(jButton5);

        jButton6.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(jButton6);

        jButton7.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(jButton7);

        jButton8.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(jButton8);

        jButton9.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(jButton9);

        jButton10.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(jButton10);

        jButton11.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(jButton11);

        jButton12.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(jButton12);

        jButton13.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(jButton13);

        jButton14.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(jButton14);

        jButton15.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(jButton15);

        jButton16.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(jButton16);

        jButton17.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(jButton17);

        jButton18.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(jButton18);

        jButton19.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(jButton19);

        jButton20.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(jButton20);

        jButton21.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(jButton21);

        jButton22.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(jButton22);

        jButton23.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(jButton23);

        jButton24.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(jButton24);

        jButton25.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(jButton25);

        jButton26.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(jButton26);

        jButton27.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(jButton27);

        jButton28.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(jButton28);

        jButton29.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(jButton29);

        jButton30.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(jButton30);

        jButton31.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(jButton31);

        jButton32.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(jButton32);

        jButton33.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(jButton33);

        jButton34.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(jButton34);

        jButton35.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(jButton35);

        jButton36.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(jButton36);

        jButton37.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(jButton37);

        jButton38.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(jButton38);

        jButton39.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(jButton39);

        jButton40.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(jButton40);

        jButton41.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(jButton41);

        jButton42.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(jButton42);

        jButton43.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(jButton43);

        jButton44.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(jButton44);

        jButton45.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(jButton45);

        jButton46.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(jButton46);

        jButton47.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(jButton47);

        jButton48.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(jButton48);

        jButton49.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(jButton49);

        jButton50.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(jButton50);

        jButton51.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(jButton51);

        jButton52.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(jButton52);

        jButton53.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(jButton53);

        jButton54.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(jButton54);

        jButton55.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(jButton55);

        jButton56.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(jButton56);

        jButton57.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(jButton57);

        jButton58.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(jButton58);

        jButton59.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(jButton59);

        jButton60.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(jButton60);

        jButton61.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(jButton61);

        jButton62.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(jButton62);

        jButton63.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(jButton63);

        jButton64.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(jButton64);

        jButton65.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(jButton65);

        jButton66.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(jButton66);

        jButton67.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButton67.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton67ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton67);

        jButton68.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(jButton68);

        jButton69.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(jButton69);

        jButton70.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(jButton70);

        jButton71.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(jButton71);

        jButton72.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(jButton72);

        jButton73.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(jButton73);

        jButton74.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(jButton74);

        jButton75.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(jButton75);

        jButton76.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(jButton76);

        jButton77.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(jButton77);

        jButton78.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(jButton78);

        jButton79.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(jButton79);

        jButton80.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(jButton80);

        jButton81.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(jButton81);

        jButton82.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(jButton82);

        jButton83.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(jButton83);

        jButton84.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(jButton84);

        jButton85.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(jButton85);

        jButton86.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(jButton86);

        jButton87.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(jButton87);

        jButton88.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(jButton88);

        jButton89.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(jButton89);

        jButton90.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(jButton90);

        jButton91.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(jButton91);

        jButton92.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(jButton92);

        jButton93.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(jButton93);

        jButton94.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(jButton94);

        jButton95.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(jButton95);

        jButton96.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(jButton96);

        jButton97.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(jButton97);

        jButton98.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(jButton98);

        jButton99.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(jButton99);

        jButton100.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButton100.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton100ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton100);

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 680, 530));

        Mazo2.setLayout(new java.awt.GridLayout(2, 3));

        jButton102.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        Mazo2.add(jButton102);

        jButton103.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        Mazo2.add(jButton103);

        jButton104.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        Mazo2.add(jButton104);

        jButton105.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        Mazo2.add(jButton105);

        jButton106.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        Mazo2.add(jButton106);

        jButton107.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        Mazo2.add(jButton107);

        getContentPane().add(Mazo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 180, 190, 100));

        Mazo.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        Mazo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MazoActionPerformed(evt);
            }
        });
        getContentPane().add(Mazo, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 390, 80, 50));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 650, 90, 10));

        NombreMazoTurno.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        NombreMazoTurno.setText("Mazo Jugador 1");
        getContentPane().add(NombreMazoTurno, new org.netbeans.lib.awtextra.AbsoluteConstraints(722, 160, 190, -1));

        jButton101.setText("CambiarTurno");
        getContentPane().add(jButton101, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 290, 120, -1));

        tiempoLabel.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        tiempoLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tiempoLabel.setText("00:00");
        tiempoLabel.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        getContentPane().add(tiempoLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 540, 130, 40));

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Carta Utilizada");
        jLabel4.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 60, 150, 70));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton100ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton100ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton100ActionPerformed

    private void jButton67ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton67ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton67ActionPerformed

    private void MazoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MazoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MazoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tablero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tablero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tablero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tablero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tablero().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JButton Mazo;
    private javax.swing.JPanel Mazo2;
    public static javax.swing.JLabel NombreMazoTurno;
    public static javax.swing.JButton jButton1;
    public static javax.swing.JButton jButton10;
    public static javax.swing.JButton jButton100;
    public static javax.swing.JButton jButton101;
    public static javax.swing.JButton jButton102;
    public static javax.swing.JButton jButton103;
    public static javax.swing.JButton jButton104;
    public static javax.swing.JButton jButton105;
    public static javax.swing.JButton jButton106;
    public static javax.swing.JButton jButton107;
    public static javax.swing.JButton jButton11;
    public static javax.swing.JButton jButton12;
    public static javax.swing.JButton jButton13;
    public static javax.swing.JButton jButton14;
    public static javax.swing.JButton jButton15;
    public static javax.swing.JButton jButton16;
    public static javax.swing.JButton jButton17;
    public static javax.swing.JButton jButton18;
    public static javax.swing.JButton jButton19;
    public static javax.swing.JButton jButton2;
    public static javax.swing.JButton jButton20;
    public static javax.swing.JButton jButton21;
    public static javax.swing.JButton jButton22;
    public static javax.swing.JButton jButton23;
    public static javax.swing.JButton jButton24;
    public static javax.swing.JButton jButton25;
    public static javax.swing.JButton jButton26;
    public static javax.swing.JButton jButton27;
    public static javax.swing.JButton jButton28;
    public static javax.swing.JButton jButton29;
    public static javax.swing.JButton jButton3;
    public static javax.swing.JButton jButton30;
    public static javax.swing.JButton jButton31;
    public static javax.swing.JButton jButton32;
    public static javax.swing.JButton jButton33;
    public static javax.swing.JButton jButton34;
    public static javax.swing.JButton jButton35;
    public static javax.swing.JButton jButton36;
    public static javax.swing.JButton jButton37;
    public static javax.swing.JButton jButton38;
    public static javax.swing.JButton jButton39;
    public static javax.swing.JButton jButton4;
    public static javax.swing.JButton jButton40;
    public static javax.swing.JButton jButton41;
    public static javax.swing.JButton jButton42;
    public static javax.swing.JButton jButton43;
    public static javax.swing.JButton jButton44;
    public static javax.swing.JButton jButton45;
    public static javax.swing.JButton jButton46;
    public static javax.swing.JButton jButton47;
    public static javax.swing.JButton jButton48;
    public static javax.swing.JButton jButton49;
    public static javax.swing.JButton jButton5;
    public static javax.swing.JButton jButton50;
    public static javax.swing.JButton jButton51;
    public static javax.swing.JButton jButton52;
    public static javax.swing.JButton jButton53;
    public static javax.swing.JButton jButton54;
    public static javax.swing.JButton jButton55;
    public static javax.swing.JButton jButton56;
    public static javax.swing.JButton jButton57;
    public static javax.swing.JButton jButton58;
    public static javax.swing.JButton jButton59;
    public static javax.swing.JButton jButton6;
    public static javax.swing.JButton jButton60;
    public static javax.swing.JButton jButton61;
    public static javax.swing.JButton jButton62;
    public static javax.swing.JButton jButton63;
    public static javax.swing.JButton jButton64;
    public static javax.swing.JButton jButton65;
    public static javax.swing.JButton jButton66;
    public static javax.swing.JButton jButton67;
    public static javax.swing.JButton jButton68;
    public static javax.swing.JButton jButton69;
    public static javax.swing.JButton jButton7;
    public static javax.swing.JButton jButton70;
    public static javax.swing.JButton jButton71;
    public static javax.swing.JButton jButton72;
    public static javax.swing.JButton jButton73;
    public static javax.swing.JButton jButton74;
    public static javax.swing.JButton jButton75;
    public static javax.swing.JButton jButton76;
    public static javax.swing.JButton jButton77;
    public static javax.swing.JButton jButton78;
    public static javax.swing.JButton jButton79;
    public static javax.swing.JButton jButton8;
    public static javax.swing.JButton jButton80;
    public static javax.swing.JButton jButton81;
    public static javax.swing.JButton jButton82;
    public static javax.swing.JButton jButton83;
    public static javax.swing.JButton jButton84;
    public static javax.swing.JButton jButton85;
    public static javax.swing.JButton jButton86;
    public static javax.swing.JButton jButton87;
    public static javax.swing.JButton jButton88;
    public static javax.swing.JButton jButton89;
    public static javax.swing.JButton jButton9;
    public static javax.swing.JButton jButton90;
    public static javax.swing.JButton jButton91;
    public static javax.swing.JButton jButton92;
    public static javax.swing.JButton jButton93;
    public static javax.swing.JButton jButton94;
    public static javax.swing.JButton jButton95;
    public static javax.swing.JButton jButton96;
    public static javax.swing.JButton jButton97;
    public static javax.swing.JButton jButton98;
    public static javax.swing.JButton jButton99;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    public static javax.swing.JLabel tiempoLabel;
    // End of variables declaration//GEN-END:variables
}
